"""
ClickHouse schema creation and pipeline write helpers.
All tables live in the `nexus` database.
"""
import logging
from datetime import datetime, timezone
from database.clickhouse_client import get_client, insert, query as ch_query

logger = logging.getLogger(__name__)


# ─── DDL ─────────────────────────────────────────────────────────────────────

_TABLES = {
    "nexus.campaigns": """
        CREATE TABLE IF NOT EXISTS nexus.campaigns (
            id         String,
            name       String,
            platform   LowCardinality(String),
            status     LowCardinality(String),
            budget     Float64,
            start_date String,
            audience   String
        ) ENGINE = ReplacingMergeTree()
        ORDER BY id
    """,

    "nexus.campaign_metrics_daily": """
        CREATE TABLE IF NOT EXISTS nexus.campaign_metrics_daily (
            campaign_id  String,
            date         Date,
            impressions  UInt64,
            clicks       UInt64,
            spend        Float64,
            revenue      Float64,
            conversions  UInt64
        ) ENGINE = ReplacingMergeTree()
        ORDER BY (campaign_id, date)
    """,

    # Derived / processed metrics per campaign per 5-minute pipeline window
    "nexus.processed_metrics": """
        CREATE TABLE IF NOT EXISTS nexus.processed_metrics (
            window_seed        UInt64,
            campaign_id        String,
            computed_at        DateTime,
            impressions        UInt64,
            clicks             UInt64,
            spend              Float64,
            revenue            Float64,
            conversions        UInt64,
            ctr                Float64,
            cpc                Float64,
            cpm                Float64,
            cpa                Float64,
            roas               Float64,
            conversion_rate    Float64,
            profit             Float64,
            budget_utilization Float64,
            health_score       Float64,
            health_category    LowCardinality(String),
            trend_direction    LowCardinality(String)
        ) ENGINE = ReplacingMergeTree()
        ORDER BY (campaign_id, window_seed)
    """,

    # Aggregate KPI snapshot per pipeline window
    "nexus.kpi_snapshots": """
        CREATE TABLE IF NOT EXISTS nexus.kpi_snapshots (
            window_seed       UInt64,
            computed_at       DateTime,
            total_spend       Float64,
            total_revenue     Float64,
            total_conversions UInt64,
            blended_roas      Float64,
            average_cpa       Float64,
            average_ctr       Float64,
            total_profit      Float64,
            ai_health_score   Float64
        ) ENGINE = ReplacingMergeTree()
        ORDER BY window_seed
    """,

    # Anomaly alerts written by the pipeline
    "nexus.alerts": """
        CREATE TABLE IF NOT EXISTS nexus.alerts (
            id            String,
            window_seed   UInt64,
            severity      LowCardinality(String),
            campaign_id   String,
            campaign_name String,
            message       String,
            detail        String,
            timestamp     String,
            created_at    DateTime
        ) ENGINE = ReplacingMergeTree()
        ORDER BY (id, window_seed)
    """,

    # AI recommendations generated by DeepSeek after reading ClickHouse data
    "nexus.ai_recommendations": """
        CREATE TABLE IF NOT EXISTS nexus.ai_recommendations (
            id             String,
            window_seed    UInt64,
            campaign_id    String,
            campaign_name  String,
            type           LowCardinality(String),
            title          String,
            description    String,
            roas_impact    Float64,
            revenue_impact Float64,
            cpa_impact     Float64,
            confidence     Float64,
            priority       LowCardinality(String),
            generated_at   DateTime
        ) ENGINE = ReplacingMergeTree()
        ORDER BY (id, window_seed)
    """,
}


def _existing_tables() -> set[str]:
    """Return the set of tables that already exist in the nexus database."""
    try:
        rows = ch_query("SHOW TABLES FROM nexus")
        return {r.get("name", "") for r in rows}
    except Exception:
        return set()


def create_tables() -> bool:
    """Create any missing nexus tables. Skips DDL entirely if schema is already complete."""
    client = get_client()
    if client is None:
        return False
    try:
        expected = {t.split(".", 1)[1] for t in _TABLES}   # bare table names
        existing = _existing_tables()

        if expected.issubset(existing):
            logger.info("ClickHouse schema already exists — skipping DDL (%d tables)", len(expected))
            return True

        # First boot or partial schema — create database + any missing tables
        client.command("CREATE DATABASE IF NOT EXISTS nexus")
        missing = {k: v for k, v in _TABLES.items() if k.split(".", 1)[1] not in existing}
        for table, ddl in missing.items():
            client.command(ddl)
            logger.info("ClickHouse table created: %s", table)
        logger.info("ClickHouse schema ready (%d new, %d existing)", len(missing), len(existing))
        return True
    except Exception as e:
        logger.error("Failed to initialise ClickHouse schema: %s", e)
        return False


# ─── Seed helpers (initial historical data) ───────────────────────────────────

def is_seeded() -> bool:
    try:
        rows = ch_query("SELECT count() AS cnt FROM nexus.campaign_metrics_daily")
        return bool(rows) and int(rows[0].get("cnt", 0)) > 0
    except Exception:
        return False


def seed(campaigns, histories: dict) -> None:
    """Write campaign metadata + 60-day daily history into ClickHouse."""
    camp_rows = [
        {
            "id": c.id,
            "name": c.name,
            "platform": c.platform.value,
            "status": c.status.value,
            "budget": float(c.budget),
            "start_date": c.start_date,
            "audience": c.target_audience,
        }
        for c in campaigns
    ]
    insert("nexus.campaigns", camp_rows)

    metric_rows = []
    for cid, history in histories.items():
        for pt in history:
            metric_rows.append({
                "campaign_id": cid,
                "date": pt["date"],
                "impressions": int(pt.get("impressions", 0)),
                "clicks":      int(pt.get("clicks", 0)),
                "spend":       float(pt.get("spend", 0)),
                "revenue":     float(pt.get("revenue", 0)),
                "conversions": int(pt.get("conversions", 0)),
            })
    if metric_rows:
        insert("nexus.campaign_metrics_daily", metric_rows)
    logger.info(
        "ClickHouse seeded: %d campaigns, %d daily rows",
        len(camp_rows), len(metric_rows),
    )


# ─── Pipeline write helpers ───────────────────────────────────────────────────

def write_processed_metrics(processed_campaigns, window_seed: int) -> None:
    """Persist derived metrics + health + trend for every campaign."""
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    rows = []
    for pc in processed_campaigns:
        m = pc.metrics
        rows.append({
            "window_seed":        window_seed,
            "campaign_id":        pc.campaign.id,
            "computed_at":        now,
            "impressions":        int(m.impressions),
            "clicks":             int(m.clicks),
            "spend":              float(m.spend),
            "revenue":            float(m.revenue),
            "conversions":        int(m.conversions),
            "ctr":                float(m.ctr),
            "cpc":                float(m.cpc),
            "cpm":                float(m.cpm),
            "cpa":                float(m.cpa),
            "roas":               float(m.roas),
            "conversion_rate":    float(m.conversion_rate),
            "profit":             float(m.profit),
            "budget_utilization": float(m.budget_utilization),
            "health_score":       float(pc.health.score),
            "health_category":    pc.health.category.value,
            "trend_direction":    pc.trend_direction.value,
        })
    if insert("nexus.processed_metrics", rows):
        logger.info("Wrote %d processed_metrics rows (window=%s)", len(rows), window_seed)


def write_kpi_snapshot(kpis, window_seed: int) -> None:
    """Persist aggregate KPIs for this pipeline window."""
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    insert("nexus.kpi_snapshots", [{
        "window_seed":       window_seed,
        "computed_at":       now,
        "total_spend":       float(kpis.total_spend),
        "total_revenue":     float(kpis.total_revenue),
        "total_conversions": int(kpis.total_conversions),
        "blended_roas":      float(kpis.blended_roas),
        "average_cpa":       float(kpis.average_cpa),
        "average_ctr":       float(kpis.average_ctr),
        "total_profit":      float(kpis.total_profit),
        "ai_health_score":   float(kpis.ai_health_score),
    }])
    logger.info("Wrote KPI snapshot (window=%s)", window_seed)


def write_alerts(alerts, window_seed: int) -> None:
    """Persist anomaly alerts for this pipeline window."""
    if not alerts:
        return
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    rows = [{
        "id":            a.id,
        "window_seed":   window_seed,
        "severity":      a.severity.value,
        "campaign_id":   a.campaign_id,
        "campaign_name": a.campaign_name,
        "message":       a.message,
        "detail":        a.detail,
        "timestamp":     a.timestamp,
        "created_at":    now,
    } for a in alerts]
    if insert("nexus.alerts", rows):
        logger.info("Wrote %d alerts (window=%s)", len(rows), window_seed)


def write_ai_recommendations(recommendations, window_seed: int) -> None:
    """Persist AI-generated recommendations for this pipeline window."""
    if not recommendations:
        return
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    rows = [{
        "id":             r.id,
        "window_seed":    window_seed,
        "campaign_id":    r.campaign_id,
        "campaign_name":  r.campaign_name,
        "type":           r.type,
        "title":          r.title,
        "description":    r.description,
        "roas_impact":    float(r.roas_impact),
        "revenue_impact": float(r.revenue_impact),
        "cpa_impact":     float(r.cpa_impact),
        "confidence":     float(r.confidence),
        "priority":       r.priority,
        "generated_at":   now,
    } for r in recommendations]
    if insert("nexus.ai_recommendations", rows):
        logger.info("Wrote %d AI recommendations (window=%s)", len(rows), window_seed)


def read_latest_recommendations(window_seed: int) -> list[dict]:
    """Read AI recommendations for the current window from ClickHouse."""
    rows = ch_query(
        "SELECT * FROM nexus.ai_recommendations WHERE window_seed = {ws:UInt64} ORDER BY confidence DESC",
        {"ws": window_seed},
    )
    return rows


# ─── Real ad-account ingestion (n8n → /api/ingest) ────────────────────────────

def has_real_campaigns() -> bool:
    """True once at least one real campaign has been ingested from a connected ad account."""
    rows = ch_query("SELECT count() AS cnt FROM nexus.campaigns")
    return bool(rows) and int(rows[0].get("cnt", 0)) > 0


def write_ingested_campaigns(account_id: str, platform: str, campaigns: list[dict]) -> int:
    """
    Upsert campaign metadata + today's daily metrics row from a real ad-platform fetch.
    `campaigns` items are shaped {campaign_id, campaign_name, impressions, clicks, spend, conversions, revenue}
    (matches the Normalize Ad Data node output in nexus_n8n_workflow.json).
    """
    if not campaigns:
        return 0

    today_date = datetime.now(timezone.utc).date()
    today_str  = today_date.isoformat()
    camp_rows, metric_rows = [], []

    for c in campaigns:
        raw_id = str(c.get("campaign_id") or "")
        if not raw_id:
            continue
        cid = f"{platform}_{raw_id}"
        spend = float(c.get("spend", 0) or 0)

        camp_rows.append({
            "id": cid,
            "name": str(c.get("campaign_name") or cid),
            "platform": platform,
            "status": "active",
            "budget": round(max(spend * 3, 100.0), 2),
            "start_date": today_str,
            "audience": "Live ad account",
        })
        metric_rows.append({
            "campaign_id": cid,
            "date": today_date,
            "impressions": int(c.get("impressions", 0) or 0),
            "clicks":      int(c.get("clicks", 0) or 0),
            "spend":       spend,
            "revenue":     float(c.get("revenue", 0) or 0),
            "conversions": int(c.get("conversions", 0) or 0),
        })

    if camp_rows:
        insert("nexus.campaigns", camp_rows)
    if metric_rows:
        insert("nexus.campaign_metrics_daily", metric_rows)

    logger.info("Ingested %d real campaigns (platform=%s, account=%s)", len(camp_rows), platform, account_id)
    return len(camp_rows)


def read_real_campaigns() -> list[dict]:
    """Metadata for every real ingested campaign (deduped via FINAL)."""
    return ch_query("SELECT * FROM nexus.campaigns FINAL ORDER BY id")


def read_real_campaign_history(campaign_id: str) -> list[dict]:
    """Full daily metric history for one real campaign, oldest first."""
    rows = ch_query(
        "SELECT * FROM nexus.campaign_metrics_daily FINAL WHERE campaign_id = {cid:String} ORDER BY date",
        {"cid": campaign_id},
    )
    return rows
