-- Run this in the ClickHouse Cloud SQL console to create the nexus database and all tables.
-- After running, click the database dropdown and switch to "nexus" to verify.

CREATE DATABASE IF NOT EXISTS nexus;

-- Campaign catalogue
CREATE TABLE IF NOT EXISTS nexus.campaigns (
    id         String,
    name       String,
    platform   LowCardinality(String),
    status     LowCardinality(String),
    budget     Float64,
    start_date String,
    audience   String
) ENGINE = ReplacingMergeTree()
ORDER BY id;

-- Raw daily metrics (historical)
CREATE TABLE IF NOT EXISTS nexus.campaign_metrics_daily (
    campaign_id  String,
    date         Date,
    impressions  UInt64,
    clicks       UInt64,
    spend        Float64,
    revenue      Float64,
    conversions  UInt64
) ENGINE = ReplacingMergeTree()
ORDER BY (campaign_id, date);

-- Derived / processed metrics per campaign per 5-minute pipeline window
CREATE TABLE IF NOT EXISTS nexus.processed_metrics (
    window_seed        UInt64,
    campaign_id        String,
    computed_at        DateTime,
    impressions        UInt64,
    clicks             UInt64,
    spend              Float64,
    revenue            Float64,
    conversions        UInt64,
    ctr                Float64,
    cpc                Float64,
    cpm                Float64,
    cpa                Float64,
    roas               Float64,
    conversion_rate    Float64,
    profit             Float64,
    budget_utilization Float64,
    health_score       Float64,
    health_category    LowCardinality(String),
    trend_direction    LowCardinality(String)
) ENGINE = ReplacingMergeTree()
ORDER BY (campaign_id, window_seed);

-- Aggregate KPI snapshot per pipeline window
CREATE TABLE IF NOT EXISTS nexus.kpi_snapshots (
    window_seed       UInt64,
    computed_at       DateTime,
    total_spend       Float64,
    total_revenue     Float64,
    total_conversions UInt64,
    blended_roas      Float64,
    average_cpa       Float64,
    average_ctr       Float64,
    total_profit      Float64,
    ai_health_score   Float64
) ENGINE = ReplacingMergeTree()
ORDER BY window_seed;

-- Anomaly alerts written by the pipeline
CREATE TABLE IF NOT EXISTS nexus.alerts (
    id            String,
    window_seed   UInt64,
    severity      LowCardinality(String),
    campaign_id   String,
    campaign_name String,
    message       String,
    detail        String,
    timestamp     String,
    created_at    DateTime
) ENGINE = ReplacingMergeTree()
ORDER BY (id, window_seed);

-- AI recommendations generated by DeepSeek after reading ClickHouse data
CREATE TABLE IF NOT EXISTS nexus.ai_recommendations (
    id             String,
    window_seed    UInt64,
    campaign_id    String,
    campaign_name  String,
    type           LowCardinality(String),
    title          String,
    description    String,
    roas_impact    Float64,
    revenue_impact Float64,
    cpa_impact     Float64,
    confidence     Float64,
    priority       LowCardinality(String),
    generated_at   DateTime
) ENGINE = ReplacingMergeTree()
ORDER BY (id, window_seed);

-- Verify: show all tables in nexus database
SHOW TABLES FROM nexus;
