"""
DeepSeek AI client — reads processed metrics from ClickHouse and generates
rich, data-grounded recommendations that are written back to ClickHouse.

Falls back to rule-based description enrichment when ClickHouse is unavailable.
"""
import os
import json
import logging
from typing import Optional
from openai import OpenAI

logger = logging.getLogger(__name__)

_client: Optional[OpenAI] = None


def get_client() -> Optional[OpenAI]:
    global _client
    if _client is not None:
        return _client

    api_key = os.getenv("DEEPSEEK_API_KEY", "")
    if not api_key:
        logger.info("DEEPSEEK_API_KEY not set — AI enrichment disabled")
        return None

    _client = OpenAI(
        api_key=api_key,
        base_url="https://api.deepseek.com",
    )
    logger.info("DeepSeek client initialized")
    return _client


def is_available() -> bool:
    return get_client() is not None


def enrich_recommendations(recommendations: list[dict]) -> list[dict]:
    """
    Lightweight enrichment: takes rule-based recommendation dicts and rewrites
    descriptions to be more specific and actionable.
    Used as a fallback when ClickHouse is not connected.
    """
    client = get_client()
    if client is None or not recommendations:
        return recommendations

    to_enrich = [r for r in recommendations if r.get("priority") == "high"][:5]
    if not to_enrich:
        return recommendations

    rec_list = json.dumps([
        {
            "id":          r["id"],
            "campaign":    r.get("campaign_name", ""),
            "platform":    r.get("platform", ""),
            "type":        r.get("type", ""),
            "title":       r["title"],
            "description": r["description"],
        }
        for r in to_enrich
    ], indent=2)

    system_prompt = (
        "You are a senior performance marketing analyst. "
        "Rewrite each recommendation description to be more specific, actionable, and data-driven. "
        "Keep each description to 2-3 sentences maximum. "
        "Return a JSON array with the same 'id' fields and a new 'description' field only."
    )

    try:
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Enrich these recommendations:\n{rec_list}"},
            ],
            max_tokens=800,
            temperature=0.3,
            response_format={"type": "json_object"},
        )
        raw = response.choices[0].message.content.strip()
        parsed = json.loads(raw)
        enriched_list = parsed if isinstance(parsed, list) else parsed.get("recommendations", [])
        enriched_map = {item["id"]: item["description"] for item in enriched_list if "id" in item}
        return [
            {**r, "description": enriched_map.get(r["id"], r["description"])}
            for r in recommendations
        ]
    except Exception as e:
        logger.warning("DeepSeek enrichment failed: %s", e)
        return recommendations


def analyze_from_clickhouse(processed_metrics: list[dict], kpi_snapshot: dict,
                             existing_recs: list[dict]) -> list[dict] | None:
    """
    Full analysis mode — DeepSeek receives processed metrics read from ClickHouse
    and generates a complete set of recommendations (not just description rewrites).

    Args:
        processed_metrics: rows from nexus.processed_metrics for the current window
        kpi_snapshot: aggregate KPIs for the current window
        existing_recs: rule-based recommendations already generated by the pipeline

    Returns:
        List of enriched recommendation dicts, or None if DeepSeek is unavailable.
    """
    client = get_client()
    if client is None or not processed_metrics:
        return None

    # Build a compact summary of the ClickHouse data for the prompt
    metrics_summary = []
    for m in processed_metrics:
        metrics_summary.append({
            "campaign_id":   m.get("campaign_id"),
            "roas":          round(float(m.get("roas", 0)), 2),
            "ctr":           round(float(m.get("ctr", 0)), 2),
            "cpa":           round(float(m.get("cpa", 0)), 2),
            "spend":         round(float(m.get("spend", 0)), 2),
            "revenue":       round(float(m.get("revenue", 0)), 2),
            "profit":        round(float(m.get("profit", 0)), 2),
            "health_score":  round(float(m.get("health_score", 0)), 1),
            "health_cat":    m.get("health_category", ""),
            "trend":         m.get("trend_direction", ""),
            "budget_util":   round(float(m.get("budget_utilization", 0)), 1),
        })

    kpi_summary = {
        "total_spend":    round(float(kpi_snapshot.get("total_spend", 0)), 2),
        "total_revenue":  round(float(kpi_snapshot.get("total_revenue", 0)), 2),
        "blended_roas":   round(float(kpi_snapshot.get("blended_roas", 0)), 2),
        "average_cpa":    round(float(kpi_snapshot.get("average_cpa", 0)), 2),
        "average_ctr":    round(float(kpi_snapshot.get("average_ctr", 0)), 2),
        "ai_health":      round(float(kpi_snapshot.get("ai_health_score", 0)), 1),
    }

    # Include existing rule-based recs as context for DeepSeek
    recs_context = [
        {"id": r["id"], "type": r.get("type"), "title": r["title"],
         "campaign_id": r.get("campaign_id"), "priority": r.get("priority")}
        for r in existing_recs
    ]

    system_prompt = (
        "You are a senior AI-powered performance marketing analyst. "
        "You have access to real-time processed advertising metrics stored in ClickHouse. "
        "Analyze the data and produce a JSON array of actionable recommendations. "
        "Each recommendation must have these fields: "
        "id (string, prefix 'ai_'), campaign_id (string), campaign_name (derive from campaign_id), "
        "type (one of: budget_optimization, bid_strategy, creative_refresh, audience_expansion, "
        "schedule_optimization, keyword_optimization), "
        "title (concise action title), description (2-3 sentence specific analysis + action), "
        "roas_impact (expected % ROAS improvement, float), revenue_impact (% revenue impact, float), "
        "cpa_impact (% CPA change — negative means improvement, float), "
        "confidence (0-100 float based on data strength), priority (high/medium/low). "
        "Return JSON object: {\"recommendations\": [...]}. "
        "Focus on campaigns with low health scores, poor ROAS, or high budget utilization. "
        "Be specific and data-driven — reference the actual numbers from the metrics."
    )

    user_content = (
        f"ClickHouse Processed Metrics (current window):\n{json.dumps(metrics_summary, indent=2)}\n\n"
        f"Aggregate KPIs:\n{json.dumps(kpi_summary, indent=2)}\n\n"
        f"Existing rule-based recommendations (use as context, improve upon them):\n"
        f"{json.dumps(recs_context, indent=2)}\n\n"
        "Generate 5-8 data-grounded recommendations based on the ClickHouse metrics above."
    )

    try:
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_content},
            ],
            max_tokens=2000,
            temperature=0.3,
            response_format={"type": "json_object"},
        )
        raw = response.choices[0].message.content.strip()
        parsed = json.loads(raw)
        recs = parsed.get("recommendations", parsed) if isinstance(parsed, dict) else parsed

        # Fill in campaign names from campaign_id if not provided
        _CAMP_NAMES = {
            "camp_001": "Summer Sale 2024",
            "camp_002": "Brand Awareness Q3",
            "camp_003": "Retargeting Cart Abandon",
            "camp_004": "LinkedIn B2B Q3",
            "camp_005": "TikTok Gen-Z",
            "camp_006": "Holiday 2024",
        }
        for r in recs:
            if "campaign_name" not in r or not r["campaign_name"]:
                r["campaign_name"] = _CAMP_NAMES.get(r.get("campaign_id", ""), "Unknown")

        logger.info("DeepSeek generated %d recommendations from ClickHouse data", len(recs))
        return recs
    except Exception as e:
        logger.warning("DeepSeek ClickHouse analysis failed: %s", e)
        return None


def generate_campaign_summary(campaign_name: str, metrics: dict) -> str:
    """Generate a 1-sentence AI summary for a campaign's current performance."""
    client = get_client()
    if client is None:
        return ""

    try:
        prompt = (
            f"Campaign: {campaign_name}\n"
            f"ROAS: {metrics.get('roas', 0):.2f}x | "
            f"CTR: {metrics.get('ctr', 0):.1f}% | "
            f"CPA: ${metrics.get('cpa', 0):.0f} | "
            f"Spend: ${metrics.get('spend', 0):.0f} | "
            f"Revenue: ${metrics.get('revenue', 0):.0f}\n\n"
            "Write a single sentence summarizing this campaign's performance and one key takeaway."
        )
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=100,
            temperature=0.3,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        logger.warning("DeepSeek campaign summary failed: %s", e)
        return ""
