name: dbt run

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: dbt seed --profiles-dir .
        env:
          DBT_CLICKHOUSE_HOST: ${{ secrets.DBT_CLICKHOUSE_HOST }}
          DBT_CLICKHOUSE_USER: ${{ secrets.DBT_CLICKHOUSE_USER }}
          DBT_CLICKHOUSE_PASSWORD: ${{ secrets.DBT_CLICKHOUSE_PASSWORD }}
      - run: dbt run --profiles-dir .
        env:
          DBT_CLICKHOUSE_HOST: ${{ secrets.DBT_CLICKHOUSE_HOST }}
          DBT_CLICKHOUSE_USER: ${{ secrets.DBT_CLICKHOUSE_USER }}
          DBT_CLICKHOUSE_PASSWORD: ${{ secrets.DBT_CLICKHOUSE_PASSWORD }}
      - run: dbt test --profiles-dir .
        env:
          DBT_CLICKHOUSE_HOST: ${{ secrets.DBT_CLICKHOUSE_HOST }}
          DBT_CLICKHOUSE_USER: ${{ secrets.DBT_CLICKHOUSE_USER }}
          DBT_CLICKHOUSE_PASSWORD: ${{ secrets.DBT_CLICKHOUSE_PASSWORD }}
